export const contactCopy = {
  es: {
    title: '¿Quieres contactar con Jeyker?',
    intro: 'Puedes consultar sus datos públicos o escribirle un mensaje aquí.',
    details: 'Ver datos de contacto', compose: 'Redactar un correo',
    editorTitle: 'Tu mensaje para Jeyker', reopen: 'Volver a editar',
    requestDetails: 'Sí, quiero ver los datos de contacto de Jeyker.',
    requestCompose: 'Quiero redactar un correo para Jeyker aquí en el chat.',
    choosing: 'El asistente está preparando su respuesta…', choiceError: 'No se pudo continuar la conversación. Vuelve a intentarlo.',
    phone: 'Teléfono', email: 'Correo', github: 'GitHub', to: 'Para',
    name: 'Tu nombre', replyEmail: 'Tu correo de respuesta (opcional)', subject: 'Asunto', message: 'Mensaje',
    namePlaceholder: '¿Cómo te llamas?', subjectPlaceholder: 'Por ejemplo: entrevista para Full Stack Engineer',
    messagePlaceholder: 'Escribe aquí lo que quieres contarle a Jeyker…',
    demo: 'Modo demostración: todavía no se envían correos reales.',
    consent: 'Al pulsar «Confirmar envío simulado», confirmas el texto que has escrito. No se incluyen el chat ni los documentos adjuntos.',
    send: 'Confirmar envío simulado', sending: 'Registrando simulación…', cancel: 'Cerrar editor',
    success: 'Simulación completada. No se ha enviado ningún correo.',
    limit: 'Ya utilizaste el único envío simulado de esta sesión. Puedes seguir consultando los datos de contacto.',
    session: 'Un envío simulado por sesión de esta pestaña, también después de recargar.',
    loading: 'Cargando contacto…', retry: 'Reintentar', required: 'Obligatorio',
    unavailable: 'El envío no está disponible. Puedes consultar los datos de contacto.',
    locked: 'Hay un intento pendiente. Conservamos el texto para reintentar sin duplicarlo. Espera 30 segundos antes de reintentar. Si recargaste y perdiste el borrador, usa los datos de contacto públicos; no se inicia otro envío.',
    usedNotice: 'Esta sesión ya utilizó su envío de contacto.',
    errors: {
      mode_changed: 'Cambió el modo de envío. Actualiza el formulario y revisa el botón antes de confirmar de nuevo.',
      locked: 'Esta sesión ya tiene otro mensaje reservado. No se puede cambiar el texto ni iniciar otro envío.',
      pending: 'No se pudo confirmar la aceptación del correo. Espera 30 segundos y reintenta el mismo mensaje; no se enviará una copia nueva.',
      rate_limited: 'Se alcanzó temporalmente el límite de contacto. Inténtalo más tarde o usa los datos públicos.',
      invalid: 'Completa tu nombre, asunto y mensaje. Si indicas un correo, revisa su formato.',
      unavailable: 'No se pudo confirmar la simulación. Puedes reintentar sin duplicarla.',
      expired: 'La sesión caducó o el servidor se reinició. No se inicia otra automáticamente. Si había un envío pendiente, podría haberse aceptado aunque ya no podamos recuperar su estado.',
      used: 'Esta sesión ya tiene una simulación registrada.',
      storage: 'El navegador no permite guardar el estado de esta pestaña. Habilita el almacenamiento de sesión para probar el envío.',
    },
    why: '¿Por qué este feature es tan cool?',
    explanation: 'El agente decide cuándo ofrecer contacto y espera tu elección. Tu decisión vuelve a la conversación: puede responder con los datos públicos o incluir este editor. Tú revisas el mensaje y confirmas la simulación. Es un flujo de decisión humana; MCP y el correo real todavía no están conectados.',
  },
  en: {
    title: 'Would you like to contact Jeyker?',
    intro: 'View his public contact details or write him a message here.',
    details: 'View contact details', compose: 'Write an email',
    editorTitle: 'Your message to Jeyker', reopen: 'Edit again',
    requestDetails: 'Yes, I would like to see Jeyker’s contact details.',
    requestCompose: 'I would like to write an email to Jeyker here in the chat.',
    choosing: 'The assistant is preparing its response…', choiceError: 'The conversation could not continue. Please try again.',
    phone: 'Phone', email: 'Email', github: 'GitHub', to: 'To',
    name: 'Your name', replyEmail: 'Your reply email (optional)', subject: 'Subject', message: 'Message',
    namePlaceholder: 'What is your name?', subjectPlaceholder: 'For example: Full Stack Engineer interview',
    messagePlaceholder: 'Write what you would like to tell Jeyker…',
    demo: 'Demo mode: no real emails are sent yet.',
    consent: 'By clicking “Confirm simulated send”, you confirm the text you wrote. The chat and attached documents are not included.',
    send: 'Confirm simulated send', sending: 'Recording simulation…', cancel: 'Close editor',
    success: 'Simulation completed. No email has been sent.',
    limit: 'You have used this session’s single simulated send. You can still view the contact details.',
    session: 'One simulated send per tab session, including after reloading.',
    loading: 'Loading contact…', retry: 'Try again', required: 'Required',
    unavailable: 'Sending is unavailable. You can view the public contact details.',
    locked: 'An attempt is pending. We keep the exact text for a safe retry. Wait 30 seconds before retrying. If you reloaded and lost the draft, use the contact details; no new send is started.',
    usedNotice: 'This session has already used its contact submission.',
    errors: {
      mode_changed: 'The delivery mode changed. Refresh the form and review the button before confirming again.',
      locked: 'This session already reserved a different message. The text cannot be changed or sent again.',
      pending: 'Email acceptance could not be confirmed. Wait 30 seconds and retry the same message; no new copy will be sent.',
      rate_limited: 'The contact limit has temporarily been reached. Try later or use the public details.',
      invalid: 'Fill in your name, subject and message. Check the email format if you provide one.',
      unavailable: 'The simulation could not be confirmed. You can retry without duplicating it.',
      expired: 'The session expired or the server restarted. No new session is started automatically. A pending email may have been accepted even though its status can no longer be recovered.',
      used: 'This session already has a recorded simulation.',
      storage: 'Your browser cannot store this tab’s state. Enable session storage to try the simulated send.',
    },
    why: 'Why is this feature so cool?',
    explanation: 'The agent decides when to offer contact and waits for your choice. Your decision returns to the conversation: it can answer with public details or embed this editor. You review the message and confirm the simulation. This is a human-decision flow; MCP and real email delivery are not connected yet.',
  },
} as const

export function contactPresentation(locale: 'es' | 'en', mode: 'simulation' | 'resend') {
  const copy = contactCopy[locale]
  if (mode === 'simulation') return copy
  return { ...copy, ...(locale === 'es' ? {
    demo: 'Envío real: el mensaje se enviará a Jeyker mediante Resend.',
    consent: 'Al pulsar «Confirmar y enviar correo», autorizas el envío de tu nombre, correo de respuesta y mensaje a Jeyker mediante Resend. No se incluyen el chat ni los documentos.',
    send: 'Confirmar y enviar correo', sending: 'Enviando…', retry: 'Consultar estado',
    success: 'Resend ha aceptado el correo para su envío. La entrega en la bandeja aún no está confirmada.',
    limit: 'Ya utilizaste el envío de esta sesión. Puedes seguir consultando los datos de contacto.',
    session: 'Un correo por sesión de esta pestaña. Las sesiones se pierden si el backend se reinicia.',
    explanation: 'El agente ofrece contacto y espera tu elección. Solo tu clic de confirmación envía el formulario mediante Resend. El backend reserva la sesión en memoria y Resend reutiliza la misma clave para evitar duplicados en los reintentos. Un reinicio pierde sesiones y contadores; esta demo usa un único proceso y réplica. El almacenamiento está separado para añadir una base de datos después. El agente no puede enviar por su cuenta. No hay conexión MCP.',
  } : {
    demo: 'Real email: this message will be sent to Jeyker through Resend.',
    consent: 'By clicking “Confirm and send email”, you authorize sending your name, reply email and message to Jeyker through Resend. The chat and documents are not included.',
    send: 'Confirm and send email', sending: 'Sending…', retry: 'Check status',
    success: 'Resend accepted the email for sending. Inbox delivery is not yet confirmed.',
    limit: 'You have used this session’s email. You can still view the contact details.',
    session: 'One email per tab session. Sessions are lost if the backend restarts.',
    explanation: 'The agent offers contact and waits for your choice. Only your confirmation click sends the form through Resend. The backend reserves the session in memory and Resend reuses the same key to prevent duplicate retries. A restart loses sessions and counters; this demo uses one process and replica. Storage is separate so a database can be added later. The agent cannot send on its own. No MCP connection is used.',
  }), errors: { ...copy.errors, unavailable: locale === 'es'
    ? 'No se pudo confirmar el envío. Consulta el estado o reintenta el mismo mensaje.'
    : 'Sending could not be confirmed. Check the status or retry the same message.' } }
}
