export const contactCopy = {
  es: {
    title: '¿Quieres contactar con Jeyker?',
    intro: 'Puedes consultar sus datos públicos o escribirle un mensaje aquí.',
    details: 'Ver datos de contacto', compose: 'Redactar un correo',
    phone: 'Teléfono', email: 'Correo', github: 'GitHub', to: 'Para',
    name: 'Tu nombre', replyEmail: 'Tu correo de respuesta (opcional)', subject: 'Asunto', message: 'Mensaje',
    namePlaceholder: '¿Cómo te llamas?', subjectPlaceholder: 'Por ejemplo: entrevista para Full Stack Engineer',
    messagePlaceholder: 'Escribe aquí lo que quieres contarle a Jeyker…',
    demo: 'Modo demostración: todavía no se envían correos reales.',
    consent: 'Al pulsar «Confirmar envío simulado», confirmas el texto que has escrito. No se incluyen el chat ni los documentos adjuntos.',
    send: 'Confirmar envío simulado', sending: 'Registrando simulación…', cancel: 'Cerrar editor',
    success: 'Simulación completada. No se ha enviado ningún correo.',
    limit: 'Ya utilizaste el único envío simulado de esta sesión. Puedes seguir consultando los datos de contacto.',
    session: 'Un envío simulado por sesión de esta pestaña, también después de recargar.',
    loading: 'Cargando contacto…', retry: 'Reintentar', required: 'Obligatorio',
    errors: {
      invalid: 'Completa tu nombre, asunto y mensaje. Si indicas un correo, revisa su formato.',
      unavailable: 'No se pudo confirmar la simulación. Puedes reintentar sin duplicarla.',
      expired: 'La sesión de contacto caducó o el servidor se reinició. No se ha iniciado otra automáticamente.',
      used: 'Esta sesión ya tiene una simulación registrada.',
      storage: 'El navegador no permite guardar el estado de esta pestaña. Habilita el almacenamiento de sesión para probar el envío.',
    },
    why: '¿Por qué este feature es tan cool?',
    explanation: 'Esto prepara un flujo Human-in-the-Loop: el agente ofrece la acción, tú revisas y editas el mensaje y solo tu clic permite registrarlo. El backend valida el nombre y limita cada sesión a una simulación. La conexión MCP y el envío real de correo llegarán después.',
  },
  en: {
    title: 'Would you like to contact Jeyker?',
    intro: 'View his public contact details or write him a message here.',
    details: 'View contact details', compose: 'Write an email',
    phone: 'Phone', email: 'Email', github: 'GitHub', to: 'To',
    name: 'Your name', replyEmail: 'Your reply email (optional)', subject: 'Subject', message: 'Message',
    namePlaceholder: 'What is your name?', subjectPlaceholder: 'For example: Full Stack Engineer interview',
    messagePlaceholder: 'Write what you would like to tell Jeyker…',
    demo: 'Demo mode: no real emails are sent yet.',
    consent: 'By clicking “Confirm simulated send”, you confirm the text you wrote. The chat and attached documents are not included.',
    send: 'Confirm simulated send', sending: 'Recording simulation…', cancel: 'Close editor',
    success: 'Simulation completed. No email has been sent.',
    limit: 'You have used this session’s single simulated send. You can still view the contact details.',
    session: 'One simulated send per tab session, including after reloading.',
    loading: 'Loading contact…', retry: 'Try again', required: 'Required',
    errors: {
      invalid: 'Fill in your name, subject and message. Check the email format if you provide one.',
      unavailable: 'The simulation could not be confirmed. You can retry without duplicating it.',
      expired: 'The contact session expired or the server restarted. A new one has not been started automatically.',
      used: 'This session already has a recorded simulation.',
      storage: 'Your browser cannot store this tab’s state. Enable session storage to try the simulated send.',
    },
    why: 'Why is this feature so cool?',
    explanation: 'This prepares a Human-in-the-Loop flow: the agent offers an action, you review and edit the message, and only your click allows it to be recorded. The backend validates the name and limits each session to one simulation. MCP and real email delivery will be connected later.',
  },
} as const
