export const contactCopy = {
  es: {
    title: '¿Quieres contactar con Jeyker?',
    intro: 'Puedes consultar sus datos públicos o escribirle un mensaje aquí.',
    details: 'Ver datos de contacto', compose: 'Redactar un correo',
    editorTitle: 'Tu mensaje para Jeyker', reopen: 'Volver a editar',
    requestDetails: 'Sí, quiero ver los datos de contacto de Jeyker.',
    requestCompose: 'Quiero redactar un correo para Jeyker aquí en el chat.',
    choosing: 'El asistente está preparando su respuesta…', choiceError: 'No se pudo continuar la conversación. Vuelve a intentarlo.',
    phone: 'Teléfono', email: 'Correo', github: 'GitHub', to: 'Para',
    name: 'Tu nombre', replyEmail: 'Tu correo de respuesta (opcional)', subject: 'Asunto', message: 'Mensaje',
    namePlaceholder: '¿Cómo te llamas?', subjectPlaceholder: 'Por ejemplo: entrevista para Full Stack Engineer',
    messagePlaceholder: 'Escribe aquí lo que quieres contarle a Jeyker…',
    demo: 'Modo demostración: todavía no se envían correos reales.',
    consent: 'Al pulsar «Confirmar envío simulado», confirmas el texto que has escrito. No se incluyen el chat ni los documentos adjuntos.',
    send: 'Confirmar envío simulado', sending: 'Registrando simulación…', cancel: 'Cerrar editor',
    success: 'Simulación completada. No se ha enviado ningún correo.',
    limit: 'Ya utilizaste el único envío simulado de esta sesión. Puedes seguir consultando los datos de contacto.',
    session: 'Un envío simulado por sesión de esta pestaña, también después de recargar.',
    loading: 'Cargando contacto…', retry: 'Reintentar', required: 'Obligatorio',
    errors: {
      invalid: 'Completa tu nombre, asunto y mensaje. Si indicas un correo, revisa su formato.',
      unavailable: 'No se pudo confirmar la simulación. Puedes reintentar sin duplicarla.',
      expired: 'La sesión de contacto caducó o el servidor se reinició. No se ha iniciado otra automáticamente.',
      used: 'Esta sesión ya tiene una simulación registrada.',
      storage: 'El navegador no permite guardar el estado de esta pestaña. Habilita el almacenamiento de sesión para probar el envío.',
    },
    why: '¿Por qué este feature es tan cool?',
    explanation: 'El agente decide cuándo ofrecer contacto y espera tu elección. Tu decisión vuelve a la conversación: puede responder con los datos públicos o incluir este editor. Tú revisas el mensaje y confirmas la simulación. Es un flujo de decisión humana; MCP y el correo real todavía no están conectados.',
  },
  en: {
    title: 'Would you like to contact Jeyker?',
    intro: 'View his public contact details or write him a message here.',
    details: 'View contact details', compose: 'Write an email',
    editorTitle: 'Your message to Jeyker', reopen: 'Edit again',
    requestDetails: 'Yes, I would like to see Jeyker’s contact details.',
    requestCompose: 'I would like to write an email to Jeyker here in the chat.',
    choosing: 'The assistant is preparing its response…', choiceError: 'The conversation could not continue. Please try again.',
    phone: 'Phone', email: 'Email', github: 'GitHub', to: 'To',
    name: 'Your name', replyEmail: 'Your reply email (optional)', subject: 'Subject', message: 'Message',
    namePlaceholder: 'What is your name?', subjectPlaceholder: 'For example: Full Stack Engineer interview',
    messagePlaceholder: 'Write what you would like to tell Jeyker…',
    demo: 'Demo mode: no real emails are sent yet.',
    consent: 'By clicking “Confirm simulated send”, you confirm the text you wrote. The chat and attached documents are not included.',
    send: 'Confirm simulated send', sending: 'Recording simulation…', cancel: 'Close editor',
    success: 'Simulation completed. No email has been sent.',
    limit: 'You have used this session’s single simulated send. You can still view the contact details.',
    session: 'One simulated send per tab session, including after reloading.',
    loading: 'Loading contact…', retry: 'Try again', required: 'Required',
    errors: {
      invalid: 'Fill in your name, subject and message. Check the email format if you provide one.',
      unavailable: 'The simulation could not be confirmed. You can retry without duplicating it.',
      expired: 'The contact session expired or the server restarted. A new one has not been started automatically.',
      used: 'This session already has a recorded simulation.',
      storage: 'Your browser cannot store this tab’s state. Enable session storage to try the simulated send.',
    },
    why: 'Why is this feature so cool?',
    explanation: 'The agent decides when to offer contact and waits for your choice. Your decision returns to the conversation: it can answer with public details or embed this editor. You review the message and confirm the simulation. This is a human-decision flow; MCP and real email delivery are not connected yet.',
  },
} as const
